version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: meetingmirror-mongo
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: meetingmirror-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data:
